source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               lib/zkex.jar,\
               lib/gson.jar,\
               lib/zkmax.jar,\
               lib/client-bind.jar,\
               lib/jackson-databind.jar,\
               lib/jackson-core.jar,\
               lib/jackson-annotations.jar,\
               lib/javassist.jar,\
               lib/zuti.jar,\
               lib/za11y.jar
jre.compilation.profile = JavaSE-17
